-- Seed watchlist. Generated by scripts/import-watchlist.ts from legacy/morning-watchlist.html.
-- Do NOT hand-edit — re-run the importer if the source HTML changes.

-- Placeholder. Populated during Phase 1.
